# Generated by Django 6.0.4 on 2026-06-13 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_dailyordercounter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailyordercounter',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
