# Generated by Django 6.0.4 on 2026-06-12 22:27

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='profile_photo',
            field=models.ImageField(blank=True, null=True, upload_to='customers/photos/'),
        ),
        migrations.CreateModel(
            name='LoyaltyAccount',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('points_balance', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='loyalty_account', to='customers.customer')),
            ],
        ),
        migrations.CreateModel(
            name='LoyaltyTransaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('txn_type', models.CharField(choices=[('EARN', 'Earn'), ('REDEEM', 'Redeem'), ('ADJUSTMENT', 'Adjustment'), ('EXPIRE', 'Expire')], max_length=20)),
                ('points', models.IntegerField()),
                ('balance_after', models.IntegerField()),
                ('reference_type', models.CharField(blank=True, default='', max_length=50)),
                ('reference_id', models.UUIDField(blank=True, null=True)),
                ('note', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='customers.loyaltyaccount')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='loyaltyaccount',
            constraint=models.CheckConstraint(condition=models.Q(('points_balance__gte', 0)), name='loyalty_balance_non_negative'),
        ),
        migrations.AddIndex(
            model_name='loyaltytransaction',
            index=models.Index(fields=['account', '-created_at'], name='customers_l_account_96dc37_idx'),
        ),
    ]
