# Generated by Django 6.0.4 on 2026-06-13 17:24

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_add_category_sequence'),
        ('customers', '0002_profile_photo_loyalty'),
        ('orders', '0004_tier_voucher'),
        ('tenants', '0003_brand_operations_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='loyaltyaccount',
            name='tier',
            field=models.CharField(choices=[('BRONZE', 'Bronze'), ('SILVER', 'Silver'), ('GOLD', 'Gold')], default='BRONZE', max_length=10),
        ),
        migrations.CreateModel(
            name='VoucherTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True, default='')),
                ('image', models.ImageField(blank=True, null=True, upload_to='vouchers/images/')),
                ('points_cost', models.PositiveIntegerField()),
                ('discount_type', models.CharField(choices=[('PERCENT', 'Percent Off'), ('FIXED', 'Fixed Amount Off'), ('FREE_ITEM', 'Free Item')], max_length=15)),
                ('discount_value', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('applicable_scope', models.CharField(choices=[('ALL', 'All Products'), ('CATEGORY', 'Specific Categories'), ('PRODUCT', 'Specific Products')], default='ALL', max_length=10)),
                ('is_active', models.BooleanField(default=True)),
                ('valid_days', models.PositiveIntegerField(default=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('applicable_categories', models.ManyToManyField(blank=True, related_name='voucher_templates', to='catalog.category')),
                ('applicable_products', models.ManyToManyField(blank=True, related_name='voucher_templates', to='catalog.brandproduct')),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='voucher_templates', to='tenants.brand')),
            ],
        ),
        migrations.CreateModel(
            name='CustomerVoucher',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('AVAILABLE', 'Available'), ('USED', 'Used'), ('EXPIRED', 'Expired')], default='AVAILABLE', max_length=10)),
                ('expires_at', models.DateTimeField()),
                ('used_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vouchers', to='customers.customer')),
                ('used_on_order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='used_vouchers', to='orders.order')),
                ('voucher_template', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='issued_vouchers', to='customers.vouchertemplate')),
            ],
        ),
        migrations.AddIndex(
            model_name='vouchertemplate',
            index=models.Index(fields=['brand', 'is_active'], name='customers_v_brand_i_963d28_idx'),
        ),
        migrations.AddIndex(
            model_name='customervoucher',
            index=models.Index(fields=['customer', 'status'], name='customers_c_custome_cc8dbd_idx'),
        ),
        migrations.AddIndex(
            model_name='customervoucher',
            index=models.Index(fields=['customer', '-created_at'], name='customers_c_custome_d770cf_idx'),
        ),
        migrations.AddIndex(
            model_name='customervoucher',
            index=models.Index(fields=['expires_at'], name='customers_c_expires_7c68a2_idx'),
        ),
    ]
