# Generated by Django 6.0.4 on 2026-05-31 07:17

import apps.tenants.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.RunSQL("SET lock_timeout = '3s'", migrations.RunSQL.noop),
        migrations.AddField(
            model_name='brand',
            name='cuisine_type',
            field=models.CharField(blank=True, default='', max_length=80),
        ),
        migrations.AddField(
            model_name='brand',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='brand',
            name='location_address',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='brand',
            name='logo_url',
            field=models.URLField(blank=True, default='', max_length=500),
        ),
        migrations.AddField(
            model_name='brand',
            name='operating_hours',
            field=models.JSONField(blank=True, default=apps.tenants.models.get_default_operating_hours),
        ),
        migrations.AddField(
            model_name='brand',
            name='phone',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
    ]
