# Generated by Django 6.0.4 on 2026-06-15 08:40

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0004_brand_banner_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='tax_rate',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
    ]
