# Generated by Django 6.0.4 on 2026-05-27 06:29

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0001_initial'),
        ('staff', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ManualSettlement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('payment_method', models.CharField(choices=[('CASH', 'Cash'), ('EDC', 'EDC')], max_length=10)),
                ('amount_received', models.DecimalField(decimal_places=2, max_digits=12)),
                ('change_given', models.DecimalField(decimal_places=2, max_digits=12)),
                ('edc_reference', models.CharField(blank=True, max_length=50, null=True)),
                ('settled_at', models.DateTimeField(auto_now_add=True)),
                ('cashier_employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='manual_settlements', to='staff.employee')),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='manual_settlement', to='orders.order')),
            ],
        ),
        migrations.CreateModel(
            name='MidtransWebhookLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('midtrans_order_id', models.CharField(db_index=True, max_length=100)),
                ('transaction_status', models.CharField(max_length=20)),
                ('signature_valid', models.BooleanField()),
                ('payload', models.JSONField()),
                ('received_at', models.DateTimeField(auto_now_add=True)),
                ('processing_result', models.CharField(choices=[('APPLIED', 'Applied'), ('IGNORED_OUT_OF_ORDER', 'Ignored Out Of Order'), ('IGNORED_DUPLICATE', 'Ignored Duplicate'), ('REJECTED_INVALID_SIG', 'Rejected Invalid Signature')], max_length=30)),
            ],
            options={
                'indexes': [models.Index(fields=['midtrans_order_id'], name='payments_mi_midtran_6a7872_idx'), models.Index(fields=['-received_at'], name='payments_mi_receive_f3bd6e_idx')],
            },
        ),
        migrations.CreateModel(
            name='PaymentTransaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('midtrans_order_id', models.CharField(db_index=True, max_length=100, unique=True)),
                ('transaction_id', models.CharField(blank=True, max_length=64, null=True)),
                ('payment_type', models.CharField(choices=[('qris', 'QRIS'), ('bank_transfer', 'Bank Transfer')], max_length=20)),
                ('gross_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('qr_string', models.TextField(blank=True, null=True)),
                ('qr_image_url', models.URLField(blank=True, null=True)),
                ('va_number', models.CharField(blank=True, max_length=40, null=True)),
                ('va_bank', models.CharField(blank=True, max_length=20, null=True)),
                ('expires_at', models.DateTimeField()),
                ('transaction_status', models.CharField(choices=[('pending', 'Pending'), ('settlement', 'Settlement'), ('expire', 'Expire'), ('deny', 'Deny'), ('cancel', 'Cancel'), ('refund', 'Refund')], max_length=20)),
                ('fraud_status', models.CharField(blank=True, max_length=20, null=True)),
                ('raw_request_payload', models.JSONField()),
                ('raw_response_payload', models.JSONField()),
                ('last_webhook_payload', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='payment_transaction', to='orders.order')),
            ],
        ),
    ]
