# Generated by Django 6.0.4 on 2026-05-27 06:29

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Table',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('label', models.CharField(max_length=20)),
                ('capacity', models.PositiveSmallIntegerField()),
                ('qr_token', models.CharField(max_length=43, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('outlet', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tables', to='tenants.outlet')),
            ],
            options={
                'indexes': [models.Index(fields=['qr_token'], name='tables_tabl_qr_toke_9cfd55_idx'), models.Index(fields=['outlet', 'is_active'], name='tables_tabl_outlet__a25ef2_idx')],
                'constraints': [models.UniqueConstraint(fields=('outlet', 'label'), name='unique_table_label_per_outlet')],
            },
        ),
    ]
