# Generated by Django 6.0.4 on 2026-05-27 06:29

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='categories', to='tenants.brand')),
            ],
        ),
        migrations.CreateModel(
            name='BrandProduct',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True)),
                ('base_price', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('image', models.ImageField(blank=True, null=True, upload_to='products/images/')),
                ('is_active', models.BooleanField(default=True)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='brand_products', to='tenants.brand')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='brand_products', to='catalog.category')),
            ],
        ),
        migrations.CreateModel(
            name='OutletProduct',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('outlet_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('stock_available', models.BooleanField(default=True)),
                ('stock_quantity', models.IntegerField(blank=True, null=True)),
                ('brand_product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='outlet_products', to='catalog.brandproduct')),
                ('outlet', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='outlet_products', to='tenants.outlet')),
            ],
        ),
        migrations.CreateModel(
            name='Promotion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('discount_type', models.CharField(choices=[('PERCENT', 'Percent'), ('FIXED', 'Fixed Amount')], max_length=10)),
                ('discount_value', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('starts_at', models.DateTimeField(db_index=True)),
                ('ends_at', models.DateTimeField(db_index=True)),
                ('is_active', models.BooleanField(default=True)),
                ('brand_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='promotions', to='catalog.brandproduct')),
            ],
        ),
        migrations.AddConstraint(
            model_name='category',
            constraint=models.UniqueConstraint(fields=('brand', 'name'), name='unique_category_name_per_brand'),
        ),
        migrations.AddIndex(
            model_name='brandproduct',
            index=models.Index(fields=['brand', 'is_active'], name='catalog_bra_brand_i_168bd8_idx'),
        ),
        migrations.AddIndex(
            model_name='outletproduct',
            index=models.Index(fields=['outlet', 'stock_available'], name='catalog_out_outlet__adddf4_idx'),
        ),
        migrations.AddConstraint(
            model_name='outletproduct',
            constraint=models.UniqueConstraint(fields=('brand_product', 'outlet'), name='unique_outlet_product'),
        ),
        migrations.AddIndex(
            model_name='promotion',
            index=models.Index(fields=['brand_product', 'is_active', 'starts_at', 'ends_at'], name='catalog_pro_brand_p_a875f2_idx'),
        ),
    ]
