# Generated by Django 6.0.4 on 2026-06-01 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='sequence',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
