# Generated by Django 6.0.4 on 2026-06-18 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_devicetoken'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='devicetoken',
            new_name='authenticat_user_id_62b3bb_idx',
            old_name='auth_device_user_id_idx',
        ),
        migrations.AlterField(
            model_name='devicetoken',
            name='user_id',
            field=models.CharField(db_index=True, max_length=64),
        ),
    ]
